package com.project.hrm.notification.enums;

public enum NotificationType {
    REQUEST_DOCUMENT_ACCESS,
    DOCUMENT_ACCESS_GRANTED,
    NEW_APPLY,
    PAYROLL_APPROVED,
    PERFORMANCE_REVIEW_REMINDER,
    NEW_DOCUMENT_UPLOADED,
    DEPARTMENT_CHANGE,
    EMPLOYEE_CREATED,
    EMPLOYEE_TERMINATED,
    RECRUITMENT_RESULT,
    DOCUMENT_APPROVAL,
    DOCUMENT_APPROVED,
    DOCUMENT_REJECTED,
    DOCUMENT_EXPIRED,
    DOCUMENT_CANCELLED,
    GENERAL_ANNOUNCEMENT
}
