package com.project.hrm.notification.enums;

public enum NotificationType {
    NEW_APPLY,

    PAYROLL_APPROVED,

    PERFORMANCE_REVIEW_REMINDER,

    DEPARTMENT_CHANGE,

    EMPLOYEE_CREATED,
    EMPLOYEE_TERMINATED,

    RECRUITMENT_RESULT,
    APPLY,

    TRAINING_REQUEST_UPDATE,

    NEW_DOCUMENT_UPLOADED,
    REQUEST_DOCUMENT_ACCESS,
    DOCUMENT_ACCESS_GRANTED,
    DOCUMENT_APPROVAL,
    DOCUMENT_APPROVED,
    DOCUMENT_REJECTED,
    DOCUMENT_EXPIRED,
    DOCUMENT_CANCELLED,

    GENERAL_ANNOUNCEMENT
}
