package com.project.hrm.notification.enums;

public enum NotificationType {
    REQUEST_DOCUMENT_ACCESS,
    NEW_APPLY,
    PAYROLL_APPROVED,
    PERFORMANCE_REVIEW_REMINDER,
    NEW_DOCUMENT_UPLOADED,
    DEPARTMENT_CHANGE,
    EMPLOYEE_CREATED,
    EMPLOYEE_TERMINATED,
    RECRUITMENT_RESULT,
    GENERAL_ANNOUNCEMENT
}
